run:
  timeout: 5m
  tests: false
  skip-dirs:
    - grammar
    - third-party

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
