[tools]
go = "1.26.0"
uv = "0.9.28"
"go:golang.org/x/tools/gopls" = "0.21.0"

[tasks."codegen:linux-amd64"]
env = {
  TARGET_GOOS = "linux",
  TARGET_GOARCH = "amd64"
}
run = "go run -v ./cmd/codegen"

[tasks."codegen:linux-arm64"]
env = {
  TARGET_GOOS = "linux",
  TARGET_GOARCH = "arm64"
}
run = "go run -v ./cmd/codegen"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."install:deps"]
run = "go get -v ./..."

[tasks."install:workspaced"]
run = "./scripts/install-workspaced.sh"

[tasks.install]
depends = ["install:*"]

[tasks."test:python"]
run = "uv run test.py"

[tasks.test]
depends = ["test:*"]

[tasks.lint]
run = "workspaced codebase lint"
env = { PATH = "{{ env.HOME }}/go/bin:{{ env.PATH }}", GOGC = "50", GOMEMLIMIT = "3GiB", GOLANGCI_LINT_CACHE = "/tmp/golangci-lint", GL_DEBUG = "linters_output,env" }

[tasks.fmt]
run = "workspaced codebase format"
env = { PATH = "{{ env.HOME }}/go/bin:{{ env.PATH }}" }

[tasks.ci]
depends = ["lint", "test"]
