name: Autorelease

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Install
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated grammars"
          title: "Update generated grammars"
          body: "Automated update of tree-sitter grammars generated code."
          branch: "codegen-update"
          delete-branch: true

      - name: CI
        run: mise run ci

      - name: Release
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "v$(date +'%Y%m%d%H%M%S')" --generate-notes

      - name: Upload Artifacts
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: grammar
          path: grammar/
